---
- name: Setup Docker on Linux
  hosts: localhost
  become: true
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc
      when: ansible_os_family == "Debian"

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        group: docker
        append: yes
      when: ansible_os_family == "Debian"

    - name: Check Docker version
      command: docker --version
      register: docker_version

    - name: Display Docker version
      debug:
        msg: "Docker version: {{ docker_version.stdout }}"

    - name: Verify Docker installation
      command: docker run hello-world
      register: docker_hello_world
      failed_when: docker_hello_world.rc != 0
      changed_when: false

    - name: Display Docker hello-world result
      debug:
        msg: "{{ docker_hello_world.stdout }}"
      when: docker_hello_world.rc == 0
